### ISSUE TITLE
Rendering of <sourcecode/>

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#21] opened 2017-09-18 12:09 UTC
In several places ([RFC6087](https://tools.ietf.org/html/rfc6087#section-3.1), [IETF Trust Legal Provisions](https://trustee.ietf.org/license-info/IETF-TLP-1.htm), [IESG statement on Copyright](https://www.ietf.org/iesg/statement/copyright.html)) the strings `<CODE BEGINS>` and `<CODE ENDS>` are specified as delimiters for source code in RFCs.  Should the v3 vocabulary specify that `<sourcecode/>` should be rendered with these delimiters?

**Comment by reschke** [comment] 2017-09-18 13:04
This is likely a duplicate of https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/8

**Comment by hildjj** [comment] 2017-09-20 16:49
Dup of #8

**Comment by levkowetz** [comment] 2017-09-20 17:12
I don't think that's quite established yet.  The question here is whether v3 should specify the rendering with `<CODE ENDS>`.  The question in #8 is subtly different.  It would be helpful if you'd comment on the issues and leaving the closing to the submitter when he/she has that power.

**Comment by ronaldtse** [comment] 2017-11-28 07:34
@levkowetz having added `<CODE BEGINS|END>` to a draft myself, I would concur that in v3, it would be preferable to utilize `<sourcecode/>` for obvious contextual reasons rather than have the author manually type `<CODE ...>` to wrap the code.

**Comment by paulehoffman** [comment] 2018-10-04 01:16
The recent discussion on the list shows that `<sourcecode>` is useful for many things that do not want `<CODE BEGINS>` inserted, and that `<CODE BEGINS>` has certain legal meanings. Thus, I'm going to close this.

**Closed by paulehoffman** 2018-10-04 01:16 UTC
Labels: duplicate
