### ISSUE TITLE
issues with extensions to <postal>

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#137] opened 2020-05-03 14:06 UTC
The motivation for this incredible complex feature (see related tickets on xml2rfc trac), as explained in https://tools.ietf.org/html/draft-levkowetz-xml2rfc-v3-implementation-notes-10#section-3.1.13, is IMHO very weak.

It would be far easier to remove the inconsistency with the HTML format spec by fixing *that* spec instead. The use case of making statistics about the countries authors come from (if really needed) could be addressed by a for more simpler extension.

If the extensions are to stay we need to:

- [ ] define all elements properly (see #101)
- [ ] define processing more clearly (not based on a concrete implementation)
- [ ] make sure that any kind of processing (insertion of defaults such as country codes, re-ordering, skipping) is somehow reflected in the preptool output

**Comment by jrlevine** [comment] 2020-05-07 22:50
I agree, if the problem is that the order of address lines is different in English and other languages, there are much simpler ways to solve it.

**Comment by reschke** [comment] 2020-05-08 07:43
We actually solved that by introducing https://greenbytes.de/tech/webdav/rfc7991.html#element.postalLine

**Comment by reschke** [comment] 2020-05-13 04:21
(see also https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/520)

**Comment by stpeter** [comment] 2021-07-14 16:44
Based on rfc-interest discussion, if we move to postalLine plus optional country then that would simplify processing. We'd still need to document that in 7991bis, of course.

**Comment by reschke** [comment] 2021-07-14 16:51
I can prepare a PR if you want me to.

**Comment by jrlevine** [comment] 2021-07-14 17:32
@reschke please do
This requires a grammar change, the first one in quite a while. Maybe we should wait and see if there are others we can batch with it.

**Comment by reschke** [comment] 2021-09-01 10:02
Here you go: https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/pull/204

**Comment by jrlevine** [comment] 2022-02-27 03:06
merged manually

**Closed by jrlevine** 2022-02-27 03:06 UTC
