### ISSUE TITLE
Clarification / authoritative list of available <area>, <workgroup> elements

### ISSUE THREAD

**Issue by ronaldtse** [rfc-format/draft-iab-xml2rfc-v3-bis#27] opened 2017-12-06 07:51 UTC
We have been working on an AsciiDoc RFC XML authoring tool (https://github.com/riboseinc/asciidoctor-rfc) and have encountered uncertainty regarding the allowed values of `<area>` and `<workgroup>`.

Currently @reschke 's `rfc2629.xslt` gives a warning like this:

For `<area>`:

> WARNING: Unknown IETF area: "internet" - should be one of: "Applications and Real-Time", "art", "General", "gen", "Internet", "int", "Operations and Management", "ops", "Routing", "rtg", "Security", "sec", "Transport", "tsv" (as of the publication date of 201711)

For `<workgroup>`:

> INFO: No need to include 'Working Group' or 'Research Group' postfix in /rfc/front/workgroup value 'Network Working Group'

However, the xml2rfc-v3 document in this repo leaves uncertainty in the actual allowed values and their representation.

Regarding `<area>`:

> Provides information about the IETF area to which this document relates (currently not used when generating documents).
> The value ought to be either the full name or the abbreviation of one of the IETF areas as listed on http://www.ietf.org/iesg/area.html A list of full names and abbreviations will be kept by the RFC Series Editor.

Regarding `<workgroup>`:

>  This element is used to specify the Working Group (IETF) or Research Group (IRTF) from which the document originates, if any. The recommended format is the official name of the Working Group (with some capitalization).
> In Internet-Drafts, this is used in the upper left corner of the boilerplate, replacing the "Network Working Group" string. Formatting software can append the words "Working Group" or "Research Group", depending on the "submissionType" property of the <rfc> element.

Is it possible to have further clarification in the RFC on what these actual values should be? 

Area:
* Should it be in full name or abbreviation? Could the RFC Series Editor provide their "full" list?
* In full name: according to the proper capitalization? Do we include the " Area" suffix in the value?

Workgroup:
* Should the suffix " Working Group" or " Research Group" be included in a submitted Internet-Draft?
* Should "(with some capitalization)" be "(with proper capitalization)"?

The best would certainly be a definite list exposed via API on the allowed values (i.e., working group names, area names), but minimally at least a clarification is necessary.

Thanks!

cc: @reschke @opoudjis
ref: https://github.com/riboseinc/asciidoctor-rfc/issues/83

**Comment by levkowetz** [comment] 2017-12-06 10:40
Hi Ronald,

My thoughts at the end:

On 2017-12-06 08:51, Ronald Tse wrote:
> We have been working on an AsciiDoc RFC XML authoring tool (https://github.com/riboseinc/asciidoctor-rfc) and have encountered uncertainty regarding the allowed values of `<area>` and `<workgroup>`.
> 
> Currently @reschke 's `rfc2629.xslt` gives a warning like this:
> 
> For `<area>`:
> 
> ```
> WARNING: Unknown IETF area: "internet" - should be one of: "Applications and Real-Time", "art", "General", "gen", "Internet", "int", "Operations and Management", "ops", "Routing", "rtg", "Security", "sec", "Transport", "tsv" (as of the publication date of 201711)
> ```
> 
> For `<workgroup>`:
> 
> ```
> INFO: No need to include 'Working Group' or 'Research Group' postfix in /rfc/front/workgroup value 'Network Working Group'
> ```
> 
> However, the xml2rfc-v3 document in this repo leaves uncertainty in the actual allowed values and their representation.
> 
> Regarding `<area>`:
> 
>> Provides information about the IETF area to which this document relates (currently not used when generating documents).
>> The value ought to be either the full name or the abbreviation of one of the IETF areas as listed on http://www.ietf.org/iesg/area.html A list of full names and abbreviations will be kept by the RFC Series Editor.
> 
> Regarding `<workgroup>`:
> 
>>  This element is used to specify the Working Group (IETF) or Research Group (IRTF) from which the document originates, if any. The recommended format is the official name of the Working Group (with some capitalization).
>> In Internet-Drafts, this is used in the upper left corner of the boilerplate, replacing the "Network Working Group" string. Formatting software can append the words "Working Group" or "Research Group", depending on the "submissionType" property of the <rfc> element.
> 
> Is it possible to have further clarification in the RFC on what these actual values should be? 
> 
> Area:
> * Should it be in full name or abbreviation? Could the RFC Series Editor provide their "full" list?
> * In full name: according to the proper capitalization? Do we include the " Area" suffix in the value?
> 
> Workgroup:
> * Should the suffix " Working Group" or " Research Group" be included in a submitted Internet-Draft?
> * Should "(with some capitalization)" be "(with proper capitalization)"?
> 
> The best would certainly be a definite list exposed via API on the allowed values (i.e., working group names, area names), but minimally at least a clarification is necessary.

I would actually prefer to leave both of these unconstrained in the tooling.

Having guidance on how to use these in the document is fine, but constraining
the values in the tools would 1) cost coding and maintenance effort which
currently doesn't seem to provide any particular benefit, and 2) make
documents which had valid content at one point in time produce warnings
at a later time, if the area or wg have changed name or been closed.

If we don't constrain the tooling, it would make sense to be more explicit in
the document about the guidance being just that, not strict constraints.


Best regards,

	Henrik

**Comment by reschke** [comment] 2017-12-06 10:53
On 2017-12-06 11:40, Henrik Levkowetz wrote:
> ...
> I would actually prefer to leave both of these unconstrained in the tooling.
> 
> Having guidance on how to use these in the document is fine, but 
> constraining
> the values in the tools would 1) cost coding and maintenance effort which
> currently doesn't seem to provide any particular benefit, and 2) make
> documents which had valid content at one point in time produce warnings
> at a later time, if the area or wg have changed name or been closed.

FWIW, rfc2629.xslt issues just warnings, and has knowledge about past 
changes in areas.

Also, if we do not check any of this metadata, it will not be filled 
properly, and be essentially useless (remember it's also not displayed 
in the generated document...).

> ...

Best regards, Julian

**Comment by levkowetz** [comment] 2017-12-06 11:31
Hi Julian,

On 2017-12-06 11:53, Julian Reschke wrote:
> On 2017-12-06 11:40, Henrik Levkowetz wrote:
>> ...
>> I would actually prefer to leave both of these unconstrained in the tooling.
>> 
>> Having guidance on how to use these in the document is fine, but 
>> constraining
>> the values in the tools would 1) cost coding and maintenance effort which
>> currently doesn't seem to provide any particular benefit, and 2) make
>> documents which had valid content at one point in time produce warnings
>> at a later time, if the area or wg have changed name or been closed.
> 
> FWIW, rfc2629.xslt issues just warnings, and has knowledge about past 
> changes in areas.
> 
> Also, if we do not check any of this metadata, it will not be filled 
> properly, and be essentially useless (remember it's also not displayed 
> in the generated document...).

But how useful is it today?  The canonical information about the area and
WG relations of a draft should be the datatracker database, which could
mean that the appropriate point at which to check the <area> and <workgroup>
element contents would be at draft submission time, not in the xml tooling, no?

Doing it that way would make sure that the content not matches one of all the
possible areas and working groups, but actually matches the area and working
group it belongs to, for a WG draft, and matches one of the active areas
and working groups, for individual drafts.

Best regards,

	Henrik

**Comment by reschke** [comment] 2017-12-06 11:40
On 2017-12-06 12:31, Henrik Levkowetz wrote:
> Hi Julian,
> 
> On 2017-12-06 11:53, Julian Reschke wrote:
>  > On 2017-12-06 11:40, Henrik Levkowetz wrote:
>  >> ...
>  >> I would actually prefer to leave both of these unconstrained in the 
> tooling.
>  >>
>  >> Having guidance on how to use these in the document is fine, but
>  >> constraining
>  >> the values in the tools would 1) cost coding and maintenance effort 
> which
>  >> currently doesn't seem to provide any particular benefit, and 2) make
>  >> documents which had valid content at one point in time produce warnings
>  >> at a later time, if the area or wg have changed name or been closed.
>  >
>  > FWIW, rfc2629.xslt issues just warnings, and has knowledge about past
>  > changes in areas.
>  >
>  > Also, if we do not check any of this metadata, it will not be filled
>  > properly, and be essentially useless (remember it's also not displayed
>  > in the generated document...).
> 
> But how useful is it today? The canonical information about the area and

I believe it is very useful today as nobody else is checking it.

> WG relations of a draft should be the datatracker database, which could
> mean that the appropriate point at which to check the <area> and <workgroup>
> element contents would be at draft submission time, not in the xml 
> tooling, no?

If it would be checked there, a check in the tooling would be less 
important; but it might still catch errors before submission time which 
I believe is good.

> Doing it that way would make sure that the content not matches one of 
> all the
> possible areas and working groups, but actually matches the area and working
> group it belongs to, for a WG draft, and matches one of the active areas
> and working groups, for individual drafts.

And yes, that would be very good.

Best regards, Julian

**Comment by levkowetz** [comment] 2017-12-06 11:49
Hi Julian,

On 2017-12-06 12:40, Julian Reschke wrote:
> On 2017-12-06 12:31, Henrik Levkowetz wrote:
>> Hi Julian,
>> 
>> On 2017-12-06 11:53, Julian Reschke wrote:
>>  > On 2017-12-06 11:40, Henrik Levkowetz wrote:
>>  >> ...
>>  >> I would actually prefer to leave both of these unconstrained in the 
>> tooling.
>>  >>
>>  >> Having guidance on how to use these in the document is fine, but
>>  >> constraining
>>  >> the values in the tools would 1) cost coding and maintenance effort 
>> which
>>  >> currently doesn't seem to provide any particular benefit, and 2) make
>>  >> documents which had valid content at one point in time produce warnings
>>  >> at a later time, if the area or wg have changed name or been closed.
>>  >
>>  > FWIW, rfc2629.xslt issues just warnings, and has knowledge about past
>>  > changes in areas.
>>  >
>>  > Also, if we do not check any of this metadata, it will not be filled
>>  > properly, and be essentially useless (remember it's also not displayed
>>  > in the generated document...).
>> 
>> But how useful is it today? The canonical information about the area and
> 
> I believe it is very useful today as nobody else is checking it.

Right.  I was actually questioning how useful the elements were today,
not how useful your checks were today :-)

>> WG relations of a draft should be the datatracker database, which could
>> mean that the appropriate point at which to check the <area> and <workgroup>
>> element contents would be at draft submission time, not in the xml 
>> tooling, no?
> 
> If it would be checked there, a check in the tooling would be less 
> important; but it might still catch errors before submission time which 
> I believe is good.

Understood.  However, that could also be an annoyance during development,
if a document was intended for an expected new working group.  I'm still
leaning towards leaving this as only guidance for usage in the RFCs.

>> Doing it that way would make sure that the content not matches one of 
>> all the
>> possible areas and working groups, but actually matches the area and working
>> group it belongs to, for a WG draft, and matches one of the active areas
>> and working groups, for individual drafts.
> 
> And yes, that would be very good.

Ok.  I'll add it to my (long) list for the datatracker.


Best,

	Henrik

**Comment by reschke** [comment] 2017-12-06 11:54
On 2017-12-06 12:49, Henrik Levkowetz wrote:
> ...
>  > I believe it is very useful today as nobody else is checking it.
> 
> Right. I was actually questioning how useful the elements were today,
> not how useful your checks were today :-)

Well, <workgroup> is used to populate the draft boilerplate. So checking 
minimal syntax aspects I believe makes sense.

>  >> WG relations of a draft should be the datatracker database, which could
>  >> mean that the appropriate point at which to check the <area> and 
> <workgroup>
>  >> element contents would be at draft submission time, not in the xml
>  >> tooling, no?
>  >
>  > If it would be checked there, a check in the tooling would be less
>  > important; but it might still catch errors before submission time which
>  > I believe is good.
> 
> Understood. However, that could also be an annoyance during development,
> if a document was intended for an expected new working group. I'm still
> leaning towards leaving this as only guidance for usage in the RFCs.

As long as the draft name does not start with "draft-ietf-", it should 
have a <workgroup> element, right?

> ...

Best regards, Julian

**Comment by levkowetz** [comment] 2017-12-06 11:59
On 2017-12-06 12:54, Julian Reschke wrote:
> On 2017-12-06 12:49, Henrik Levkowetz wrote:
>> ...
>>  > I believe it is very useful today as nobody else is checking it.
>> 
>> Right. I was actually questioning how useful the elements were today,
>> not how useful your checks were today :-)
> 
> Well, <workgroup> is used to populate the draft boilerplate. So checking 
> minimal syntax aspects I believe makes sense.

For some April 1st documents, it might be desirable for it to not make that
kind of sense ,:-)

>>  >> WG relations of a draft should be the datatracker database, which could
>>  >> mean that the appropriate point at which to check the <area> and 
>> <workgroup>
>>  >> element contents would be at draft submission time, not in the xml
>>  >> tooling, no?
>>  >
>>  > If it would be checked there, a check in the tooling would be less
>>  > important; but it might still catch errors before submission time which
>>  > I believe is good.
>> 
>> Understood. However, that could also be an annoyance during development,
>> if a document was intended for an expected new working group. I'm still
>> leaning towards leaving this as only guidance for usage in the RFCs.
> 
> As long as the draft name does not start with "draft-ietf-", it should 
> have a <workgroup> element, right?

No, there's a fallback, and if I remember correctly, pretty much any text
is permissible.


Best,

	Henrik

**Comment by stpeter** [comment] 2021-06-21 17:49
Discussion in the XML change management team led to the conclusion that this is not an issue for the v3 vocabulary (it wouldn't be desirable to update the XML schema with allowable values every time a new IETF working group or IRTF research group is created!). It might be more relevant for IDnits. We suggest marking as WONTFIX because not directly relevant to the v3 vocabulary, but we will bring it to the attention of the tools team with respect to IDnits.

**Closed** 2021-07-08 23:29 UTC
Labels: wontfix

**Comment by ronaldtse** [comment] 2021-07-11 04:21
Thanks @stpeter for the authoritative answer here. The original intent was not to update the XML schema per new content but to have a controlled vocabulary for draft authors, which could potentially be as simple as exposing the accepted values for `<area>` and `<workgroup>` from Datatracker via some defined endpoint.

From an authoring tooling perspective now, it would be easiest to treat the `<area>` and `<workgroup>` elements as accepting freeform text.
